void addElement(E obj)
int capacity()
void copyInto(Object[] anArray)
E elementAt(int index)
Enumeration<E> elements()
void ensureCapacity(int minCapacity)
E firstElement()
int indexOf(Object o, int index)
void insertElementAt(E obj, int index)
E lastElement()
int lastIndexOf(Object o, int index)
void removeAllElements()
boolean removeElement(Object obj)
void removeElementAt(int index)
void setElementAt(E obj, int index)
void setSize(int newSize)
void trimToSize()